### ISSUE TITLE
The radius

### ISSUE THREAD

**Issue by hhucyl** [williamgilpin/hspmc#1]
Hi, I was looking into your code, and I guess overlap is the radius or diameter of the hard spheres?

**Comment by williamgilpin** [comment]
Hello, in the `isoverlap` functions the "overlap" variable indeed denotes the diameter of the hard spheres. For this reason, if the distance between two sphere centroids is less than their diameter, then they will register as overlapping (they are then rejected by the Monte Carlo sampling)

**Comment by hhucyl** [comment]
Thank you
